/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ClienteNsg;
import dao.Cliente_DAO_Nsg;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author u09229145165
 */
public class JDlgClienteNsg extends javax.swing.JDialog {
    private boolean incluindo;
    private MaskFormatter mascaraNascimento, mascaraRG, mascaraCPF, mascaraCEP, mascaraCelular;
    public ClienteNsg clienteNsg;
    public Cliente_DAO_Nsg cliente_DAO_Nsg;

    /**
     * Creates new form ClienteNsg
     */
    public JDlgClienteNsg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Clientes");
        setLocationRelativeTo(null);
        Util.habilitar(false,jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
    
        try {
        mascaraNascimento = new MaskFormatter("##/##/####");
        mascaraRG = new MaskFormatter("#.###.###");
        mascaraCPF = new MaskFormatter("###.###.###-##");
        mascaraCEP = new MaskFormatter("#####-###");
        mascaraCelular = new MaskFormatter("(##)#####-####");
    } catch (ParseException ex) {
        Logger.getLogger(JDlgClienteNsg.class.getName()).log(Level.SEVERE, null, ex);
    }
         jFmtCpf_Nsg.setFormatterFactory(new DefaultFormatterFactory(mascaraCPF));
         jFmtNascimento_Nsg.setFormatterFactory(new DefaultFormatterFactory(mascaraNascimento));
         jFmtCep_Nsg.setFormatterFactory(new DefaultFormatterFactory(mascaraCEP));
         jFmtRg_Nsg.setFormatterFactory(new DefaultFormatterFactory(mascaraRG));
         jFmtCelular_Nsg.setFormatterFactory(new DefaultFormatterFactory(mascaraCelular));
        
    }
    
    public ClienteNsg viewBean() {
        ClienteNsg clienteNsg = new ClienteNsg();
       
        clienteNsg.setIdClienteNsg(Util.strInt(jTxtCodigo_Nsg.getText()));
        clienteNsg.setNomeNsg(jTxtNome_Nsg.getText());
        clienteNsg.setGeneroNsg(jTxtGenero_Nsg.getText());
        clienteNsg.setProfissaoNsg(jTxtProfissao_Nsg.getText());
       
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            clienteNsg.setNascimentoNsg (formato.parse(jFmtNascimento_Nsg.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgClienteNsg.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        clienteNsg.setRgNsg(jFmtRg_Nsg.getText());
        clienteNsg.setCpfNsg(jFmtCpf_Nsg.getText());
        clienteNsg.setEmailNsg(jTxtEmail_Nsg.getText());
        clienteNsg.setCelularNsg(jFmtCelular_Nsg.getText());
        clienteNsg.setCepNsg(jFmtCep_Nsg.getText());
        clienteNsg.setEnderecoNsg(jTxtEndereco_Nsg.getText());
        clienteNsg.setNumeroNsg(jTxtNumero_Nsg.getText());
        clienteNsg.setBairroNsg(jTxtBairro_Nsg.getText());
        clienteNsg.setCidadeNsg(jTxtCidade_Nsg.getText());
        clienteNsg.setUfNsg(jTxtUf_Nsg.getText());
        clienteNsg.setComplementoNsg(jTxtComplemento_Nsg.getText());
        
        return clienteNsg;
       
    }
    
    public void beanView(ClienteNsg clienteNsg) {
        String id = String.valueOf(clienteNsg.getIdClienteNsg());
       
        jTxtCodigo_Nsg.setText(id);
        jTxtNome_Nsg.setText(clienteNsg.getNomeNsg());
        jTxtGenero_Nsg.setText(clienteNsg.getGeneroNsg());
        jTxtProfissao_Nsg.setText(clienteNsg.getProfissaoNsg());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jFmtNascimento_Nsg.setText(formato.format (clienteNsg.getNascimentoNsg()));
        jFmtRg_Nsg.setText(clienteNsg.getRgNsg());
        jFmtCpf_Nsg.setText(clienteNsg.getCpfNsg());
        jTxtEmail_Nsg.setText(clienteNsg.getEmailNsg());
        jFmtCelular_Nsg.setText(clienteNsg.getCelularNsg());
        jFmtCep_Nsg.setText(clienteNsg.getCepNsg());
        jTxtEndereco_Nsg.setText(clienteNsg.getEnderecoNsg());
        jTxtNumero_Nsg.setText(clienteNsg.getNumeroNsg());
        jTxtBairro_Nsg.setText(clienteNsg.getBairroNsg());
        jTxtCidade_Nsg.setText(clienteNsg.getCidadeNsg());
        jTxtUf_Nsg.setText(clienteNsg.getUfNsg());
        jTxtComplemento_Nsg.setText(clienteNsg.getComplementoNsg());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTxtNome_Nsg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBtnIncluir_Nsg = new javax.swing.JButton();
        jTxtGenero_Nsg = new javax.swing.JTextField();
        jBtnAlterar_Nsg = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBtnExcluir_Nsg = new javax.swing.JButton();
        jFmtRg_Nsg = new javax.swing.JFormattedTextField();
        jBtnConfirmar_Nsg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBtnCancelar_Nsg = new javax.swing.JButton();
        jFmtNascimento_Nsg = new javax.swing.JFormattedTextField();
        jBtnPesquisar_Nsg = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo_Nsg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtProfissao_Nsg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jFmtCpf_Nsg = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtEmail_Nsg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jFmtCelular_Nsg = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTxtEndereco_Nsg = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTxtBairro_Nsg = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtCidade_Nsg = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTxtComplemento_Nsg = new javax.swing.JTextField();
        jTxtUf_Nsg = new javax.swing.JTextField();
        jTxtNumero_Nsg = new javax.swing.JTextField();
        jFmtCep_Nsg = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Nome");

        jLabel3.setText("Gênero");

        jBtnIncluir_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/04 - incluir.png"))); // NOI18N
        jBtnIncluir_Nsg.setText("Incluir");
        jBtnIncluir_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_NsgActionPerformed(evt);
            }
        });

        jTxtGenero_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtGenero_NsgActionPerformed(evt);
            }
        });

        jBtnAlterar_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01 - alterar.png"))); // NOI18N
        jBtnAlterar_Nsg.setText("Alerar");
        jBtnAlterar_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_NsgActionPerformed(evt);
            }
        });

        jLabel4.setText("RG");

        jBtnExcluir_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/02 - excluir.png"))); // NOI18N
        jBtnExcluir_Nsg.setText("Excluir");
        jBtnExcluir_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_NsgActionPerformed(evt);
            }
        });

        jBtnConfirmar_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/07 - confirmar.png"))); // NOI18N
        jBtnConfirmar_Nsg.setText("Confirmar");
        jBtnConfirmar_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_NsgActionPerformed(evt);
            }
        });

        jLabel5.setText("Nascimento");

        jBtnCancelar_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/03 - exit.png"))); // NOI18N
        jBtnCancelar_Nsg.setText("Cancelar");
        jBtnCancelar_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_NsgActionPerformed(evt);
            }
        });

        jBtnPesquisar_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/06 - pesquisar.png"))); // NOI18N
        jBtnPesquisar_Nsg.setText("Pesquisar");
        jBtnPesquisar_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_NsgActionPerformed(evt);
            }
        });

        jLabel6.setText("Complemento");

        jLabel1.setText("Código Cliente");

        jTxtCodigo_Nsg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtCodigo_NsgFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCodigo_NsgFocusLost(evt);
            }
        });
        jTxtCodigo_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigo_NsgActionPerformed(evt);
            }
        });

        jLabel8.setText("Profissão");

        jTxtProfissao_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtProfissao_NsgActionPerformed(evt);
            }
        });

        jLabel9.setText("CPF");

        jLabel10.setText("E-mail");

        jTxtEmail_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmail_NsgActionPerformed(evt);
            }
        });

        jLabel11.setText("Celular");

        jLabel12.setText("CEP");

        jLabel13.setText("Endereço");

        jTxtEndereco_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEndereco_NsgActionPerformed(evt);
            }
        });

        jLabel14.setText("Número");

        jLabel15.setText("Bairro");

        jTxtBairro_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBairro_NsgActionPerformed(evt);
            }
        });

        jLabel16.setText("Cidade");

        jTxtCidade_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCidade_NsgActionPerformed(evt);
            }
        });

        jLabel17.setText("UF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jTxtCodigo_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jFmtNascimento_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtEmail_Nsg)
                            .addComponent(jTxtProfissao_Nsg)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jFmtRg_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jFmtCpf_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTxtGenero_Nsg)
                            .addComponent(jTxtNome_Nsg)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jFmtCelular_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(161, 161, 161))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jTxtEndereco_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtNumero_Nsg)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jTxtBairro_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jTxtCidade_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(64, 64, 64))
                                    .addComponent(jTxtUf_Nsg)))
                            .addComponent(jTxtComplemento_Nsg, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jFmtCep_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnIncluir_Nsg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnAlterar_Nsg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnExcluir_Nsg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnConfirmar_Nsg))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jBtnCancelar_Nsg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnPesquisar_Nsg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtCodigo_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtNome_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtGenero_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtProfissao_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFmtNascimento_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFmtRg_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFmtCpf_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtEmail_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFmtCelular_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtCep_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtEndereco_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtNumero_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtBairro_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtCidade_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtUf_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(31, 31, 31)))
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtComplemento_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir_Nsg)
                    .addComponent(jBtnAlterar_Nsg)
                    .addComponent(jBtnExcluir_Nsg)
                    .addComponent(jBtnConfirmar_Nsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar_Nsg)
                    .addComponent(jBtnPesquisar_Nsg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluir_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_NsgActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jBtnConfirmar_Nsg, jBtnCancelar_Nsg, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
        Util.habilitar(false, jBtnIncluir_Nsg, jBtnAlterar_Nsg, jBtnExcluir_Nsg, jBtnPesquisar_Nsg);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
        
        incluindo = true;
    }//GEN-LAST:event_jBtnIncluir_NsgActionPerformed

    private void jTxtGenero_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtGenero_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtGenero_NsgActionPerformed

    private void jBtnAlterar_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_NsgActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jBtnConfirmar_Nsg, jBtnCancelar_Nsg, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
        Util.habilitar(false, jBtnIncluir_Nsg, jBtnAlterar_Nsg, jBtnExcluir_Nsg, jBtnPesquisar_Nsg);
        
        incluindo = false;
    }//GEN-LAST:event_jBtnAlterar_NsgActionPerformed

    private void jBtnExcluir_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_NsgActionPerformed
        // TODO add your handling code here:
       if (Util.perguntar("Deseja excluir o projeto?") == true){
       clienteNsg = viewBean();
       cliente_DAO_Nsg.delete(clienteNsg);
       Util.mensagem("Excluído com sucesso");
       }else {
                Util.mensagem("Exclusão cancelada");
                }
       
       Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
        Util.habilitar(false, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
    }//GEN-LAST:event_jBtnExcluir_NsgActionPerformed

    private void jBtnConfirmar_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_NsgActionPerformed
        // TODO add your handling code here:
        clienteNsg = viewBean();
        
        if (incluindo == true) {
            cliente_DAO_Nsg.insert(clienteNsg);
        } else {
            cliente_DAO_Nsg.update(clienteNsg);
        }
        
        Util.habilitar(false, jBtnConfirmar_Nsg, jBtnCancelar_Nsg, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
        Util.habilitar(true, jBtnIncluir_Nsg, jBtnAlterar_Nsg, jBtnExcluir_Nsg, jBtnPesquisar_Nsg);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
    }//GEN-LAST:event_jBtnConfirmar_NsgActionPerformed

    private void jBtnCancelar_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_NsgActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jBtnConfirmar_Nsg, jBtnCancelar_Nsg, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
        Util.habilitar(true, jBtnIncluir_Nsg, jBtnAlterar_Nsg, jBtnExcluir_Nsg, jBtnPesquisar_Nsg);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
        Util.mensagem("Operação cancelada com sucesso!");
    }//GEN-LAST:event_jBtnCancelar_NsgActionPerformed

    private void jBtnPesquisar_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_NsgActionPerformed
        // TODO add your handling code here:
        JDlgClientePesquisaNsg jDlgClientePesquisaNsg = new JDlgClientePesquisaNsg(null, true);
        jDlgClientePesquisaNsg.setTelaAnterior(this);
        jDlgClientePesquisaNsg.setVisible(true);
       Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtGenero_Nsg, jTxtProfissao_Nsg, jFmtNascimento_Nsg, jFmtRg_Nsg, jFmtCpf_Nsg, jTxtEmail_Nsg, jFmtCelular_Nsg, jFmtCep_Nsg, jTxtEndereco_Nsg, jTxtNumero_Nsg, jTxtBairro_Nsg, jTxtCidade_Nsg, jTxtUf_Nsg, jTxtComplemento_Nsg);
    }//GEN-LAST:event_jBtnPesquisar_NsgActionPerformed

    private void jTxtCodigo_NsgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigo_NsgFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigo_NsgFocusGained

    private void jTxtCodigo_NsgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigo_NsgFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigo_NsgFocusLost

    private void jTxtCodigo_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigo_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigo_NsgActionPerformed

    private void jTxtProfissao_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtProfissao_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtProfissao_NsgActionPerformed

    private void jTxtEmail_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmail_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmail_NsgActionPerformed

    private void jTxtEndereco_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEndereco_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEndereco_NsgActionPerformed

    private void jTxtBairro_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBairro_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBairro_NsgActionPerformed

    private void jTxtCidade_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCidade_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCidade_NsgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgClienteNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgClienteNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgClienteNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgClienteNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgClienteNsg dialog = new JDlgClienteNsg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar_Nsg;
    private javax.swing.JButton jBtnCancelar_Nsg;
    private javax.swing.JButton jBtnConfirmar_Nsg;
    private javax.swing.JButton jBtnExcluir_Nsg;
    private javax.swing.JButton jBtnIncluir_Nsg;
    private javax.swing.JButton jBtnPesquisar_Nsg;
    private javax.swing.JFormattedTextField jFmtCelular_Nsg;
    private javax.swing.JFormattedTextField jFmtCep_Nsg;
    private javax.swing.JFormattedTextField jFmtCpf_Nsg;
    private javax.swing.JFormattedTextField jFmtNascimento_Nsg;
    private javax.swing.JFormattedTextField jFmtRg_Nsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtBairro_Nsg;
    private javax.swing.JTextField jTxtCidade_Nsg;
    private javax.swing.JTextField jTxtCodigo_Nsg;
    private javax.swing.JTextField jTxtComplemento_Nsg;
    private javax.swing.JTextField jTxtEmail_Nsg;
    private javax.swing.JTextField jTxtEndereco_Nsg;
    private javax.swing.JTextField jTxtGenero_Nsg;
    private javax.swing.JTextField jTxtNome_Nsg;
    private javax.swing.JTextField jTxtNumero_Nsg;
    private javax.swing.JTextField jTxtProfissao_Nsg;
    private javax.swing.JTextField jTxtUf_Nsg;
    // End of variables declaration//GEN-END:variables
}
