/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.UsuariosNsg;
import dao.Usuarios_DAO_Nsg;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author u09229145165
 */
public class JDlgUsuariosNsg extends javax.swing.JDialog {
    private boolean incluindo;
    public UsuariosNsg usuariosNsg;
    public Usuarios_DAO_Nsg usuarios_DAO_Nsg;
    private MaskFormatter mascaraCPF, mascaraNascimento;
    /**
     * Creates new form UsuariosNsg
     */
    public JDlgUsuariosNsg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        usuarios_DAO_Nsg = new Usuarios_DAO_Nsg();
        setTitle("Usuários");
        setLocationRelativeTo(null);
        Util.habilitar(false, jBtnConfirmar_Nsg1, jBtnCancelar_Nsg1, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
    
        try {
            mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraNascimento = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuariosNsg.class.getName()).log(Level.SEVERE, null, ex);
        }
          
         jFmtCpf_Nsg.setFormatterFactory(new DefaultFormatterFactory(mascaraCPF));
         jFmtNascimento_Nsg.setFormatterFactory(new DefaultFormatterFactory(mascaraNascimento));
         
    }
        public UsuariosNsg viewBean() {
        UsuariosNsg usuariosNsg = new UsuariosNsg();
       
        usuariosNsg.setIdUsuariosNsg(Util.strInt(jTxtCodigo_Nsg.getText()));
        usuariosNsg.setNomeNsg(jTxtNome_Nsg.getText());
        usuariosNsg.setApelidoNsg(jTxtApelido_Nsg.getText());
        usuariosNsg.setCpfNsg(jFmtCpf_Nsg.getText());
       
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            usuariosNsg.setNascimentoNsg (formato.parse(jFmtNascimento_Nsg.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgClienteNsg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        usuariosNsg.setNivelNsg(jCboNivel_Nsg.getSelectedIndex());
        usuariosNsg.setAtivoNsg( jChbAtivo_Nsg.isSelected() == true ? "S" : "N");
        usuariosNsg.setSenhaNsg(jPswSenha_Nsg.getText());
        
        return usuariosNsg;
       
    }
    
    public void beanView(UsuariosNsg usuariosNsg) {
        String id = String.valueOf(usuariosNsg.getIdUsuariosNsg());
       
        jTxtCodigo_Nsg.setText(id);
        jTxtNome_Nsg.setText(usuariosNsg.getNomeNsg());
        jTxtApelido_Nsg.setText(usuariosNsg.getApelidoNsg());
        jFmtCpf_Nsg.setText(usuariosNsg.getCpfNsg());
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jFmtNascimento_Nsg.setText(formato.format(usuariosNsg.getNascimentoNsg()));
        
        jCboNivel_Nsg.setSelectedIndex(usuariosNsg.getNivelNsg());
        
        if (usuariosNsg.getAtivoNsg().equals("S") == true) {
            jChbAtivo_Nsg.setSelected(true);
        } else {
            jChbAtivo_Nsg.setSelected(false);
        }
        jPswSenha_Nsg.setText(usuariosNsg.getSenhaNsg());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnAlterar_Nsg = new javax.swing.JButton();
        jBtnExcluir_Nsg = new javax.swing.JButton();
        jBtnConfirmar_Nsg = new javax.swing.JButton();
        jBtnCancelar_Nsg = new javax.swing.JButton();
        jBtnPesquisar_Nsg = new javax.swing.JButton();
        jBtnIncluir_Nsg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtCodigo_Nsg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtNome_Nsg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtApelido_Nsg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFmtCpf_Nsg = new javax.swing.JFormattedTextField();
        jFmtNascimento_Nsg = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCboNivel_Nsg = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jChbAtivo_Nsg = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jPswSenha_Nsg = new javax.swing.JPasswordField();
        jBtnAlterar_Nsg1 = new javax.swing.JButton();
        jBtnExcluir_Nsg1 = new javax.swing.JButton();
        jBtnConfirmar_Nsg1 = new javax.swing.JButton();
        jBtnCancelar_Nsg1 = new javax.swing.JButton();
        jBtnPesquisar_Nsg1 = new javax.swing.JButton();
        jBtnIncluir_Nsg1 = new javax.swing.JButton();

        jBtnAlterar_Nsg.setText("Alerar");

        jBtnExcluir_Nsg.setText("Excluir");

        jBtnConfirmar_Nsg.setText("Confirmar");

        jBtnCancelar_Nsg.setText("Cancelar");

        jBtnPesquisar_Nsg.setText("Pesquisar");

        jBtnIncluir_Nsg.setText("Incluir");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Centaur", 2, 36)); // NOI18N
        jLabel1.setText("Usuários");

        jLabel2.setText("Código");

        jLabel3.setText("Nome");

        jLabel4.setText("Apelido");

        jLabel5.setText("CPF");

        jFmtCpf_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpf_NsgActionPerformed(evt);
            }
        });

        jFmtNascimento_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtNascimento_NsgActionPerformed(evt);
            }
        });

        jLabel7.setText("Nascimento");

        jLabel6.setText("Nível");

        jCboNivel_Nsg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher nível", "Baixo", "Médio", "Alto" }));

        jLabel8.setText("Ativo");

        jChbAtivo_Nsg.setText("Sim");

        jLabel9.setText("Senha");

        jBtnAlterar_Nsg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01 - alterar.png"))); // NOI18N
        jBtnAlterar_Nsg1.setText("Alerar");
        jBtnAlterar_Nsg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_Nsg1ActionPerformed(evt);
            }
        });

        jBtnExcluir_Nsg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/02 - excluir.png"))); // NOI18N
        jBtnExcluir_Nsg1.setText("Excluir");
        jBtnExcluir_Nsg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_Nsg1ActionPerformed(evt);
            }
        });

        jBtnConfirmar_Nsg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/07 - confirmar.png"))); // NOI18N
        jBtnConfirmar_Nsg1.setText("Confirmar");
        jBtnConfirmar_Nsg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_Nsg1ActionPerformed(evt);
            }
        });

        jBtnCancelar_Nsg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/03 - exit.png"))); // NOI18N
        jBtnCancelar_Nsg1.setText("Cancelar");
        jBtnCancelar_Nsg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_Nsg1ActionPerformed(evt);
            }
        });

        jBtnPesquisar_Nsg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/06 - pesquisar.png"))); // NOI18N
        jBtnPesquisar_Nsg1.setText("Pesquisar");
        jBtnPesquisar_Nsg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_Nsg1ActionPerformed(evt);
            }
        });

        jBtnIncluir_Nsg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/04 - incluir.png"))); // NOI18N
        jBtnIncluir_Nsg1.setText("Incluir");
        jBtnIncluir_Nsg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_Nsg1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCboNivel_Nsg, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                .addComponent(jFmtCpf_Nsg, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtNome_Nsg, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtApelido_Nsg, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(jFmtNascimento_Nsg))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jChbAtivo_Nsg))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jPswSenha_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTxtCodigo_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir_Nsg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar_Nsg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir_Nsg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar_Nsg1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jBtnCancelar_Nsg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar_Nsg1)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCodigo_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNome_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtApelido_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtCpf_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtNascimento_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboNivel_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbAtivo_Nsg)
                            .addComponent(jPswSenha_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAlterar_Nsg1)
                    .addComponent(jBtnExcluir_Nsg1)
                    .addComponent(jBtnConfirmar_Nsg1)
                    .addComponent(jBtnIncluir_Nsg1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar_Nsg1)
                    .addComponent(jBtnPesquisar_Nsg1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFmtCpf_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpf_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCpf_NsgActionPerformed

    private void jFmtNascimento_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtNascimento_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtNascimento_NsgActionPerformed

    private void jBtnAlterar_Nsg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_Nsg1ActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jBtnConfirmar_Nsg1, jBtnCancelar_Nsg1, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.habilitar(false, jBtnIncluir_Nsg1, jBtnAlterar_Nsg1, jBtnExcluir_Nsg1, jBtnPesquisar_Nsg1);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        incluindo = false;
    }//GEN-LAST:event_jBtnAlterar_Nsg1ActionPerformed

    private void jBtnExcluir_Nsg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_Nsg1ActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja excluir o projeto?") == true){
            usuariosNsg = viewBean();
            usuarios_DAO_Nsg.delete(usuariosNsg);
            Util.mensagem("Excluído com sucesso");
        }else {
            Util.mensagem("Exclusão cancelada");
        }

        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
    }//GEN-LAST:event_jBtnExcluir_Nsg1ActionPerformed

    private void jBtnConfirmar_Nsg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_Nsg1ActionPerformed
        // TODO add your handling code here:
        usuariosNsg = viewBean();
        if (incluindo == true) {
            usuarios_DAO_Nsg.insert(usuariosNsg);
        } else {
            usuarios_DAO_Nsg.update(usuariosNsg);
        }
        Util.habilitar(false, jBtnConfirmar_Nsg1, jBtnCancelar_Nsg1, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.habilitar(true, jBtnIncluir_Nsg1, jBtnAlterar_Nsg1, jBtnExcluir_Nsg1, jBtnPesquisar_Nsg1);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
    }//GEN-LAST:event_jBtnConfirmar_Nsg1ActionPerformed

    private void jBtnCancelar_Nsg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_Nsg1ActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jBtnConfirmar_Nsg1, jBtnCancelar_Nsg1, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.habilitar(true, jBtnIncluir_Nsg1, jBtnAlterar_Nsg1, jBtnExcluir_Nsg1, jBtnPesquisar_Nsg1);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.mensagem("Operação cancelada");
    }//GEN-LAST:event_jBtnCancelar_Nsg1ActionPerformed

    private void jBtnPesquisar_Nsg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_Nsg1ActionPerformed
        // TODO add your handling code here:
        JDlgUsuariosPesquisaNsg jDlgUsuariosPesquisaNsg = new JDlgUsuariosPesquisaNsg(null, true);
        jDlgUsuariosPesquisaNsg.setTelaAnterior(this);
        jDlgUsuariosPesquisaNsg.setVisible(true);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
    }//GEN-LAST:event_jBtnPesquisar_Nsg1ActionPerformed

    private void jBtnIncluir_Nsg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_Nsg1ActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jBtnConfirmar_Nsg1, jBtnCancelar_Nsg1, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.habilitar(false, jBtnIncluir_Nsg1, jBtnAlterar_Nsg1, jBtnExcluir_Nsg1, jBtnPesquisar_Nsg1);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        incluindo = true;
    }//GEN-LAST:event_jBtnIncluir_Nsg1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuariosNsg dialog = new JDlgUsuariosNsg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar_Nsg;
    private javax.swing.JButton jBtnAlterar_Nsg1;
    private javax.swing.JButton jBtnCancelar_Nsg;
    private javax.swing.JButton jBtnCancelar_Nsg1;
    private javax.swing.JButton jBtnConfirmar_Nsg;
    private javax.swing.JButton jBtnConfirmar_Nsg1;
    private javax.swing.JButton jBtnExcluir_Nsg;
    private javax.swing.JButton jBtnExcluir_Nsg1;
    private javax.swing.JButton jBtnIncluir_Nsg;
    private javax.swing.JButton jBtnIncluir_Nsg1;
    private javax.swing.JButton jBtnPesquisar_Nsg;
    private javax.swing.JButton jBtnPesquisar_Nsg1;
    private javax.swing.JComboBox<String> jCboNivel_Nsg;
    private javax.swing.JCheckBox jChbAtivo_Nsg;
    private javax.swing.JFormattedTextField jFmtCpf_Nsg;
    private javax.swing.JFormattedTextField jFmtNascimento_Nsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPswSenha_Nsg;
    private javax.swing.JTextField jTxtApelido_Nsg;
    private javax.swing.JTextField jTxtCodigo_Nsg;
    private javax.swing.JTextField jTxtNome_Nsg;
    // End of variables declaration//GEN-END:variables
}
