/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author nayar
 */
public class JFrmPrincipalNsg extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipalNsg
     */
    public JFrmPrincipalNsg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuPrincipal_ebg = new javax.swing.JMenu();
        jMnuClientes_ebg = new javax.swing.JMenuItem();
        jMnuUsuarios_ebg = new javax.swing.JMenuItem();
        jMenuVendedor_ebg = new javax.swing.JMenuItem();
        jMenuProduto_ebg = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSair_ebg = new javax.swing.JMenuItem();
        jMnuMovimento_ebg = new javax.swing.JMenu();
        jMnuVendas_ebg = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuPrincipal_ebg.setMnemonic('P');
        jMnuPrincipal_ebg.setText("Principal");

        jMnuClientes_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/09 - cliente.png"))); // NOI18N
        jMnuClientes_ebg.setText("Clientes");
        jMnuClientes_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientes_ebgActionPerformed(evt);
            }
        });
        jMnuPrincipal_ebg.add(jMnuClientes_ebg);

        jMnuUsuarios_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/08 - usuario.png"))); // NOI18N
        jMnuUsuarios_ebg.setMnemonic('U');
        jMnuUsuarios_ebg.setText("Usuários");
        jMnuUsuarios_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios_ebgActionPerformed(evt);
            }
        });
        jMnuPrincipal_ebg.add(jMnuUsuarios_ebg);

        jMenuVendedor_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuVendedor_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/12 - caixa.png"))); // NOI18N
        jMenuVendedor_ebg.setText("Vendedor");
        jMenuVendedor_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendedor_ebgActionPerformed(evt);
            }
        });
        jMnuPrincipal_ebg.add(jMenuVendedor_ebg);

        jMenuProduto_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuProduto_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/14 - compra.png"))); // NOI18N
        jMenuProduto_ebg.setText("Produto");
        jMnuPrincipal_ebg.add(jMenuProduto_ebg);
        jMnuPrincipal_ebg.add(jSeparator1);

        jMenuSair_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSair_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/03 - exit.png"))); // NOI18N
        jMenuSair_ebg.setText("Sair");
        jMenuSair_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSair_ebgActionPerformed(evt);
            }
        });
        jMnuPrincipal_ebg.add(jMenuSair_ebg);

        jMenuBar1.add(jMnuPrincipal_ebg);

        jMnuMovimento_ebg.setText("Movimento");

        jMnuVendas_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/13 - venda.png"))); // NOI18N
        jMnuVendas_ebg.setText("Vendas");
        jMnuVendas_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendas_ebgActionPerformed(evt);
            }
        });
        jMnuMovimento_ebg.add(jMnuVendas_ebg);

        jMenuBar1.add(jMnuMovimento_ebg);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClientes_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientes_ebgActionPerformed
        // TODO add your handling code here:
        JDlgClienteNsg jDlgClienteNsg = new JDlgClienteNsg(null, true);
        jDlgClienteNsg.setVisible(true);
    }//GEN-LAST:event_jMnuClientes_ebgActionPerformed

    private void jMnuUsuarios_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios_ebgActionPerformed
        // TODO add your handling code here:
        JDlgUsuariosNsg jDlgUsuariosNsg = new JDlgUsuariosNsg(null, true);
        jDlgUsuariosNsg.setVisible(true);
    }//GEN-LAST:event_jMnuUsuarios_ebgActionPerformed

    private void jMenuVendedor_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendedor_ebgActionPerformed
        // TODO add your handling code here:
        JDlgVendedorNsg jDlgVendedorNsg = new JDlgVendedorNsg(null, true);
        jDlgVendedorNsg.setVisible(true);
    }//GEN-LAST:event_jMenuVendedor_ebgActionPerformed

    private void jMenuSair_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSair_ebgActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSair_ebgActionPerformed

    private void jMnuVendas_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendas_ebgActionPerformed
        // TODO add your handling code here:
        JDlgVendaNsg jDlgVendaNsg = new JDlgVendaNsg(null, true);
        jDlgVendaNsg.setVisible(true);
    }//GEN-LAST:event_jMnuVendas_ebgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipalNsg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuProduto_ebg;
    private javax.swing.JMenuItem jMenuSair_ebg;
    private javax.swing.JMenuItem jMenuVendedor_ebg;
    private javax.swing.JMenuItem jMnuClientes_ebg;
    private javax.swing.JMenu jMnuMovimento_ebg;
    private javax.swing.JMenu jMnuPrincipal_ebg;
    private javax.swing.JMenuItem jMnuUsuarios_ebg;
    private javax.swing.JMenuItem jMnuVendas_ebg;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
