package bean;
// Generated 13/09/2023 13:19:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoNsg generated by hbm2java
 */
@Entity
@Table(name="produto_nsg"
    ,catalog="db_nayara_silva"
)
public class ProdutoNsg  implements java.io.Serializable {


     private int idProdutoNsg;
     private String valorUnitNsg;
     private String saborNsg;
     private String unidadeNsg;
     private String massaNsg;
     private String modoNsg;
     private String tamanhoNsg;
     private String retirarNsg;
     private Set vendaProdutoNsgs = new HashSet(0);

    public ProdutoNsg() {
    }

	
    public ProdutoNsg(int idProdutoNsg, String valorUnitNsg, String saborNsg, String unidadeNsg, String massaNsg, String modoNsg, String tamanhoNsg, String retirarNsg) {
        this.idProdutoNsg = idProdutoNsg;
        this.valorUnitNsg = valorUnitNsg;
        this.saborNsg = saborNsg;
        this.unidadeNsg = unidadeNsg;
        this.massaNsg = massaNsg;
        this.modoNsg = modoNsg;
        this.tamanhoNsg = tamanhoNsg;
        this.retirarNsg = retirarNsg;
    }
    public ProdutoNsg(int idProdutoNsg, String valorUnitNsg, String saborNsg, String unidadeNsg, String massaNsg, String modoNsg, String tamanhoNsg, String retirarNsg, Set vendaProdutoNsgs) {
       this.idProdutoNsg = idProdutoNsg;
       this.valorUnitNsg = valorUnitNsg;
       this.saborNsg = saborNsg;
       this.unidadeNsg = unidadeNsg;
       this.massaNsg = massaNsg;
       this.modoNsg = modoNsg;
       this.tamanhoNsg = tamanhoNsg;
       this.retirarNsg = retirarNsg;
       this.vendaProdutoNsgs = vendaProdutoNsgs;
    }
   
     @Id 

    
    @Column(name="id_produto_nsg", unique=true, nullable=false)
    public int getIdProdutoNsg() {
        return this.idProdutoNsg;
    }
    
    public void setIdProdutoNsg(int idProdutoNsg) {
        this.idProdutoNsg = idProdutoNsg;
    }

    
    @Column(name="valor_unit_nsg", nullable=false, length=80)
    public String getValorUnitNsg() {
        return this.valorUnitNsg;
    }
    
    public void setValorUnitNsg(String valorUnitNsg) {
        this.valorUnitNsg = valorUnitNsg;
    }

    
    @Column(name="sabor_nsg", nullable=false, length=80)
    public String getSaborNsg() {
        return this.saborNsg;
    }
    
    public void setSaborNsg(String saborNsg) {
        this.saborNsg = saborNsg;
    }

    
    @Column(name="unidade_nsg", nullable=false, length=80)
    public String getUnidadeNsg() {
        return this.unidadeNsg;
    }
    
    public void setUnidadeNsg(String unidadeNsg) {
        this.unidadeNsg = unidadeNsg;
    }

    
    @Column(name="massa_nsg", nullable=false, length=80)
    public String getMassaNsg() {
        return this.massaNsg;
    }
    
    public void setMassaNsg(String massaNsg) {
        this.massaNsg = massaNsg;
    }

    
    @Column(name="modo_nsg", nullable=false, length=80)
    public String getModoNsg() {
        return this.modoNsg;
    }
    
    public void setModoNsg(String modoNsg) {
        this.modoNsg = modoNsg;
    }

    
    @Column(name="tamanho_nsg", nullable=false, length=80)
    public String getTamanhoNsg() {
        return this.tamanhoNsg;
    }
    
    public void setTamanhoNsg(String tamanhoNsg) {
        this.tamanhoNsg = tamanhoNsg;
    }

    
    @Column(name="retirar_nsg", nullable=false, length=80)
    public String getRetirarNsg() {
        return this.retirarNsg;
    }
    
    public void setRetirarNsg(String retirarNsg) {
        this.retirarNsg = retirarNsg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produtoNsg")
    public Set getVendaProdutoNsgs() {
        return this.vendaProdutoNsgs;
    }
    
    public void setVendaProdutoNsgs(Set vendaProdutoNsgs) {
        this.vendaProdutoNsgs = vendaProdutoNsgs;
    }




}


