package bean;
// Generated 13/09/2023 13:19:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendedorNsg generated by hbm2java
 */
@Entity
@Table(name="vendedor_nsg"
    ,catalog="db_nayara_silva"
)
public class VendedorNsg  implements java.io.Serializable {


     private int idVendedorNsg;
     private String nomeNsg;
     private String cpfNsg;
     private String celularNsg;
     private Date expedienteNsg;
     private String comissaoNsg;
     private Set vendaProdutoNsgs = new HashSet(0);
     private Set vendaNsgs = new HashSet(0);

    public VendedorNsg() {
    }

	
    public VendedorNsg(int idVendedorNsg, String nomeNsg, String cpfNsg, String celularNsg, Date expedienteNsg, String comissaoNsg) {
        this.idVendedorNsg = idVendedorNsg;
        this.nomeNsg = nomeNsg;
        this.cpfNsg = cpfNsg;
        this.celularNsg = celularNsg;
        this.expedienteNsg = expedienteNsg;
        this.comissaoNsg = comissaoNsg;
    }
    public VendedorNsg(int idVendedorNsg, String nomeNsg, String cpfNsg, String celularNsg, Date expedienteNsg, String comissaoNsg, Set vendaProdutoNsgs, Set vendaNsgs) {
       this.idVendedorNsg = idVendedorNsg;
       this.nomeNsg = nomeNsg;
       this.cpfNsg = cpfNsg;
       this.celularNsg = celularNsg;
       this.expedienteNsg = expedienteNsg;
       this.comissaoNsg = comissaoNsg;
       this.vendaProdutoNsgs = vendaProdutoNsgs;
       this.vendaNsgs = vendaNsgs;
    }
   
     @Id 

    
    @Column(name="id_vendedor_nsg", unique=true, nullable=false)
    public int getIdVendedorNsg() {
        return this.idVendedorNsg;
    }
    
    public void setIdVendedorNsg(int idVendedorNsg) {
        this.idVendedorNsg = idVendedorNsg;
    }

    
    @Column(name="nome_nsg", nullable=false, length=80)
    public String getNomeNsg() {
        return this.nomeNsg;
    }
    
    public void setNomeNsg(String nomeNsg) {
        this.nomeNsg = nomeNsg;
    }

    
    @Column(name="cpf_nsg", nullable=false, length=80)
    public String getCpfNsg() {
        return this.cpfNsg;
    }
    
    public void setCpfNsg(String cpfNsg) {
        this.cpfNsg = cpfNsg;
    }

    
    @Column(name="celular_nsg", nullable=false, length=80)
    public String getCelularNsg() {
        return this.celularNsg;
    }
    
    public void setCelularNsg(String celularNsg) {
        this.celularNsg = celularNsg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expediente_nsg", nullable=false, length=10)
    public Date getExpedienteNsg() {
        return this.expedienteNsg;
    }
    
    public void setExpedienteNsg(Date expedienteNsg) {
        this.expedienteNsg = expedienteNsg;
    }

    
    @Column(name="comissao_nsg", nullable=false, length=80)
    public String getComissaoNsg() {
        return this.comissaoNsg;
    }
    
    public void setComissaoNsg(String comissaoNsg) {
        this.comissaoNsg = comissaoNsg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedorNsg")
    public Set getVendaProdutoNsgs() {
        return this.vendaProdutoNsgs;
    }
    
    public void setVendaProdutoNsgs(Set vendaProdutoNsgs) {
        this.vendaProdutoNsgs = vendaProdutoNsgs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedorNsg")
    public Set getVendaNsgs() {
        return this.vendaNsgs;
    }
    
    public void setVendaNsgs(Set vendaNsgs) {
        this.vendaNsgs = vendaNsgs;
    }




}


